refactor: add PATH_LOGS for clear_docker

diff --git a/scripts/clear_docker b/scripts/clear_docker
--- a/scripts/clear_docker
+++ b/scripts/clear_docker
@@ -1,23 +1,26 @@
 #!/usr/bin/env bash
 
+PATH_LOGS="$HOME/.clear_docker_logs"
 
-if ! [[ -d "./.clear_docker_logs" ]]
+
+if ! [[ -d "$PATH_LOGS" ]]
 then
-    mkdir "./.clear_docker_logs"
+    mkdir "$PATH_LOGS"
 fi
 
 
 function clear_volumes() {
     echo "start clear volumes"
-    echo $(date) >> ./.clear_docker_logs/docker_volumes.log
-    echo $(date) >> ./.clear_docker_logs/docker_volumes.err
+    echo $(date) >> "$PATH_LOGS/volumes.log"
+    echo $(date) >> "$PATH_LOGS/volumes.err"
 
-    docker volume ls --filter dangling=true --filter name="^[a-f0-9]{64}$" | awk '{print $2}' | tail -n +2 | xargs -r docker volume rm \
-        >> ./.clear_docker_logs/docker_volumes.log \
-        2>> ./.clear_docker_logs/docker_volumes.err
+    docker volume ls --filter dangling=true --filter name="^[a-f0-9]{64}$" \
+        | awk '{print $2}' | tail -n +2 | xargs -r docker volume rm \
+        >> "$PATH_LOGS/volumes.log" \
+        2>> "$PATH_LOGS/volumes.err"
 
-    echo "" >> ./.clear_docker_logs/docker_volumes.log
-    echo "" >> ./.clear_docker_logs/docker_volumes.err
+    echo "" >> "$PATH_LOGS/volumes.log"
+    echo "" >> "$PATH_LOGS/volumes.err"
 
     echo "end clear volumes"
 }
@@ -25,15 +28,15 @@ function clear_volumes() {
 
 function clear_images() {
     echo "start clear images"
-    echo $(date) >> ./.clear_docker_logs/docker_images.log
-    echo $(date) >> ./.clear_docker_logs/docker_images.err
+    echo $(date) >> "$PATH_LOGS/images.log"
+    echo $(date) >> "$PATH_LOGS/images.err"
 
     docker image ls --filter dangling=true | awk '{print $3}' | tail -n +2 | xargs -r docker rmi \
-        >> ./.clear_docker_logs/docker_images.log \
-        2>> ./.clear_docker_logs/docker_images.err
+        >> "$PATH_LOGS/images.log" \
+        2>> "$PATH_LOGS/images.err"
 
-    echo "" >> ./.clear_docker_logs/docker_images.log
-    echo "" >> ./.clear_docker_logs/docker_images.err
+    echo "" >> "$PATH_LOGS/images.log"
+    echo "" >> "$PATH_LOGS/images.err"
 
     echo "end clear images"
 }
@@ -41,15 +44,15 @@ function clear_images() {
 
 function clear_build() {
     echo "start clear build"
-    echo $(date) >> ./.clear_docker_logs/docker_build.log
-    echo $(date) >> ./.clear_docker_logs/docker_build.err
+    echo $(date) >> "$PATH_LOGS/build.log"
+    echo $(date) >> "$PATH_LOGS/build.err"
 
     echo "y" | docker builder prune \
-        >> ./.clear_docker_logs/docker_build.log \
-        2>> ./.clear_docker_logs/docker_build.err
+        >> "$PATH_LOGS/build.log" \
+        2>> "$PATH_LOGS/build.err"
 
-    echo "" >> ./.clear_docker_logs/docker_build.log
-    echo "" >> ./.clear_docker_logs/docker_build.err
+    echo "" >> "$PATH_LOGS/build.log"
+    echo "" >> "$PATH_LOGS/build.err"
 
     echo "end clear build"
 }
@@ -77,7 +80,7 @@ case $1 in
         echo "-a | --all - clear all"
         ;;
     *)
-        echo "error. Use: option -h"
+        echo "Error. Use: option -h"
         ;;
 esac
 
